server:
  port: 80

spring:
  application:
    name: order-comsumer-hystrix-80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka/,http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${spring.application.name}
ribbon:
  # 读写资源时间
  ReadTimeout: 5000
  # 建立连接时间
  ConnectTimeout: 5000
# feign启动支持Hystrix fallback
feign:
  hystrix:
    enabled: true