server:
  port: 7001
# 注册名称
eureka:
  instance:
    # 服务实例名称
    hostname: euraka.com.7001
  client:
    # 禁止注册中心注册自己
    register-with-eureka: true
    # 表示该服务就是注册中心不需要检索服务
    fetch-registry: true
    service-url:
      # 设置与Eureka server交互的地址查询服务和注册服务都依赖这个地址
      defaultZone: http://localhost:7002/eureka/