# 端口号
server:
  port: 80
# 模块名称
spring:
  application:
    name: cloud-consumer-order-consul-80
  cloud:
    consul:
      host: 139.224.113.113
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        heartbeat:
          enabled: true