server:
  port: 9502

spring:
  application:
    name: gateway-service-02
  cloud:
    gateway:
      routes:
        - id: path_route_01
          # lb://表示服务均衡（loadBalance） gateway会去注册中心获取地址
          # uri: http://localhost:8002
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/discovery,/payment/get/{id}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}